// <auto-generated />
using System;
using BitcoinApp.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitcoinApp.Server.Migrations
{
    [DbContext(typeof(BitcoinDbContext))]
    [Migration("20260120071005_ExtendColumnsForTableBitcoinValueRecords")]
    partial class ExtendColumnsForTableBitcoinValueRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitcoinApp.Server.Database.Dto.BitcoinValueRecord", b =>
                {
                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<decimal>("ValueCzk")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ValueEur")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("RetrievedAt");

                    b.ToTable("BitcoinValueRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
